WebAppVentaDSI/Models/DetalleComprobante.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace WebAppVentaDSI.Models
{
    public class DetalleComprobante
    {
        [Key]
        [Display(Name = "ID")]
        public int IdDetalleComprobante { get; set; }

        [Display(Name = "Cantidad")]
        public int CantidadDetalleComprobante { set; get; }

        public int IdProducto { get; set; }

        public int IdComprobante { get; set; }

        [ForeignKey("IdProducto")]
        public virtual Producto Producto { get; set; }

        [ForeignKey("IdComprobante")]
        public virtual Comprobante Comprobante { get; set; }
    }
}

WebAppVentaDSI/Controllers/DetalleComprobanteController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebAppVentaDSI.Data.DataAcces;
using WebAppVentaDSI.Data.Interface;
using WebAppVentaDSI.Models;
using X.PagedList;

namespace WebAppVentaDSI.Controllers
{
    [Authorize]
    public class DetalleComprobanteController : Controller
    {
        private readonly IDADetalleComprobante DADetalleComprobante;
        private readonly IDAProducto DAProducto;
        private readonly IDAComprobante DAComprobante;
        public DetalleComprobanteController(IDADetalleComprobante DADetalleComprobante, IDAProducto DAProducto, IDAComprobante DAComprobante)
        {
            this.DADetalleComprobante = DADetalleComprobante; 
            this.DAProducto = DAProducto;
            this.DAComprobante = DAComprobante;
        }

        public List<double> lista(IEnumerable<DetalleComprobante> informacion)
            {
                var resultado = new List<double>();
                double total = 0;
                foreach (var item in informacion)
                {
                    total = (item.CantidadDetalleComprobante * item.Producto.PrecioVentaProducto);
                    resultado.Add(total);
                }
                return resultado;
            }
        public double Total(int id)
        {
            double total = 0;
            var info = DADetalleComprobante.GetDetalleComprobante();
            foreach (var item in info)
            {
                if (item.IdComprobante==id)
                {
                    total += (item.CantidadDetalleComprobante * item.Producto.PrecioVentaProducto);
                }
            }

            return total;
        }

        public String Condicion(int id)
        {
            string condicion = "";
            //para saber cuanto pago:
            double detallepago = 0;
            var detpago = new DADetalleTipoPago().GetDetalleTipoPago();
            foreach (var item in detpago)
            {
                if (item.IdComprobante==id)
                {
                    detallepago += item.PagoDetallePago;
                }
            }
            //para saber cuando debe pagar:
            var detcomp = DADetalleComprobante.GetDetalleComprobante();
            double detallecomp = 0;
            foreach (var item in detcomp)
            {
                if (item.IdComprobante==id)
                {
                    detallecomp += (item.CantidadDetalleComprobante*item.Producto.PrecioVentaProducto);
                }
            }
            double total = detallecomp - detallepago;
            if (total<=0)
            {
                condicion = "Cancelado";
            }
            else
            {
                condicion = "SinCancelar";
            }
            return condicion;
        }
        

        public IActionResult Index( int id, int page=1)
            {
            //var model = new DADetalleComprobante();
            var pagenumber = page;
                var DC = DADetalleComprobante.GetDetalleComprobante();
                    DC=(from tbl in DC where tbl.IdComprobante == id select tbl ).ToList();
                //if (filterByName != null)
                //{
                //    var filtro = (from tbl in DC
                //                  where tbl.Comprobante.Cliente.NombreCliente.ToLower().Contains(filterByName.ToLower())
                //                  select tbl).ToList();
                //    var model = filtro.OrderByDescending(d => d.IdDetalleComprobante).ToList().ToPagedList(pagenumber, 8);
                //    var envio = lista(model); 
                //    ViewBag.Total = envio;
                //   // DC = filtro;
                //    TempData["info"] = model;
                //    ViewBag.DetPag = Condicion(id);
                //}
                //else
                //{
                    var model = DC.OrderByDescending(d => d.IdDetalleComprobante).ToList().ToPagedList(pagenumber, 8);
                    var envio = lista(model);
                    ViewBag.Total = envio;
                    TempData["info"] = model;
                    ViewBag.DetPag = Condicion(id);
                //}
                TempData["IdComp"] = id;
                return View();
            }

            public IActionResult Create( int id)
            {
                //Listar Producto
                //var infoProducto = new DAProducto();
                ViewBag.InfoProducto = DAProducto.GetProducto();
                

            if (id==0)
            {
                var info = new DAComprobante().GetComprobante();
                var cod = (from tbl in info orderby tbl.IdComprobante descending select tbl.IdComprobante).ToList();//primer valor
                int pos = cod.ElementAt(0);
                ViewBag.InfoComprobante = pos;
                ViewBag.InfoTotal ="Total:  S/"+ Total(pos)+".00";


            }
            else
            {
                ViewBag.InfoComprobante = id;
                ViewBag.InfoTotal = "Total:  S/"+Total(id)+".00";
            }
                //Listar Comprobantes
                //var infoComprobante = new DAComprobante();
                

                return View();
            }

            [HttpPost]
            public IActionResult Create(DetalleComprobante Entidad)
            {
                Entidad.IdDetalleComprobante = 0;
                //var model = new DADetalleComprobante();
                var resultado = DADetalleComprobante.InsertDetalleComprobanteDet(Entidad);
                if (resultado > 0)
                {
                //TempData["n"] = Entidad.IdComprobante;
                    return RedirectToAction("Create");
                }
                else
                {
                    return View(resultado);
                }
            }
            public IActionResult Edit(int id)
            {
                //var ProductoEdit = new DAProducto();
                ViewBag.ProductoEdit = DAProducto.GetProducto();

                //var ComprobanteEdit = new DAComprobante();
                ViewBag.ComprobanteEdit = DAComprobante.GetComprobante();

                //var model = new DADetalleComprobante();
                var resultado = DADetalleComprobante.GetIdDetalleComprobante(id);
                return View(resultado);
            }

            [HttpPost]
            public IActionResult Edit(DetalleComprobante detalleComprobante)
            {

                //var model = new DADetalleComprobante();
                var resultao = DADetalleComprobante.UpdateDetalleComprobante(detalleComprobante);
                if (resultao)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(detalleComprobante);
                }
            }

            public IActionResult Details(int id)
            {
                //var datos = new DADetalleComprobante();
                var model = DADetalleComprobante.GetIdDetalleComprobante(id);
                return View(model);
            }

            public IActionResult Delete(int id)
            {
                //var modelodelete = new DADetalleComprobante();
                var model = DADetalleComprobante.GetIdDetalleComprobante(id);
                var resultado = DADetalleComprobante.DeleteDetalleComprobante(id);
            
                return RedirectToAction("Index",new { id = model.IdComprobante  });
            }
        }
}

WebAppVentaDSI/Controllers/DetalleTipoPagoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebAppVentaDSI.Data.DataAcces;
using WebAppVentaDSI.Data.Interface;
using WebAppVentaDSI.Models;

namespace WebAppVentaDSI.Controllers
{
    [Authorize]
    public class DetalleTipoPagoController : Controller
    {
        private readonly IDATipoPago DATipoPago;
        private readonly IDAComprobante DAComprobante;
        private readonly IDADetalleTipoPago DADetalleTipoPago;
        private readonly IDADetalleComprobante DADetalleComprobante;

        public DetalleTipoPagoController(IDATipoPago DATipoPago, IDAComprobante DAComprobante, IDADetalleTipoPago DADetalleTipoPago, IDADetalleComprobante DADetalleComprobante)
        {
            this.DATipoPago = DATipoPago;
            this.DAComprobante = DAComprobante;
            this.DADetalleTipoPago = DADetalleTipoPago;
            this.DADetalleComprobante = DADetalleComprobante;
        }

        //Lista de pago pendiente:
        public double PagoTotalReal(int id)
        {
            double resultado=0 ;

            double realizado = PagRealizado(id);
            double pendiente = PagPendiente(id);
            resultado = pendiente - realizado;

            return resultado;
        }






        //Pagos Realizados
        public double PagRealizado(int idComprobante)
        {
            //var resultado = new List<double>();
            var comprobante = DAComprobante.GetComprobante();
            var detallepago = DADetalleTipoPago.GetDetalleTipoPago();
            double total = 0;

            //for (int i = 0; i < comprobante.Count(); i++)
            //{
                for (int j = 0; j < detallepago.Count(); j++)
                {
                    if (idComprobante == detallepago.ElementAt(j).IdComprobante)
                    {
                        total += detallepago.ElementAt(j).PagoDetallePago;
                    }
                }
                //resultado.Add(total);
                //total = 0;
            //}

            return total;
        }

        



        //Lo que debe pagar
        public double PagPendiente(int idComprobante)
        {


            //var resultado = new List<double>();
            var comprobante = DAComprobante.GetComprobante();
            var detallepago = new DADetalleComprobante().GetDetalleComprobante();
            double total = 0;

            //for (int i = 0; i < comprobante.Count(); i++)
            //{
            for (int j = 0; j < detallepago.Count(); j++)
            {
                if (idComprobante == detallepago.ElementAt(j).IdComprobante)
                {
                    total += detallepago.ElementAt(j).CantidadDetalleComprobante*detallepago.ElementAt(j).Producto.PrecioVentaProducto;
                }
            }
            //resultado.Add(total);
            //total = 0;
            //}
            return total;
        }






        public IActionResult Index()
        {

            return View();
        }

        public IActionResult Create(int id)
        {
            if (id == 0)
            {


                var info = DADetalleComprobante.GetDetalleComprobante();
                var idC = (from tbl in info orderby tbl.IdDetalleComprobante descending select tbl).ToList();
                ViewBag.PagRealizado = PagRealizado(idC.ElementAt(0).IdComprobante);

                ViewBag.PagPendiente = PagPendiente(idC.ElementAt(0).IdComprobante);
                ViewBag.PagoReal = PagoTotalReal(idC.ElementAt(0).IdComprobante);

                ViewBag.InfoTipoPago = new DATipoPago().GetTipoPago();


                ViewBag.InfoComprobante = idC.ElementAt(0).IdComprobante;
            }
            else
            {
                ViewBag.PagRealizado = PagRealizado(id);

                ViewBag.PagPendiente = PagPendiente(id);
                ViewBag.PagoReal = PagoTotalReal(id);

                ViewBag.InfoTipoPago = new DATipoPago().GetTipoPago();


                ViewBag.InfoComprobante = id;
            }

            

            return View();
        }

        [HttpPost]
        public IActionResult Create(DetalleTipoPago Entidad)
        {
            Entidad.IdDetalleTipoPago = 0;
            //evaluamos los pagos
            //pago total realizado real
            double pagoRealizado = PagRealizado(Entidad.IdComprobante)+Entidad.PagoDetallePago;
            //el total que debe pagar
            double pagoTotal = PagPendiente(Entidad.IdComprobante);
            //evaluar el pago
            double Pagado = pagoTotal - pagoRealizado;
            //exacto
            if (Pagado == 0)
            {
                var resultado = new DADetalleTipoPago().InsertarDetalleTipoPago(Entidad);
                if (resultado > 0)
                {
                    return RedirectToAction("Index", "Comprobante");
                }
                else
                {
                    return View(resultado);
                }
                //pago menos, faltan pagos
            }else if (Pagado>0)
            {
                var resultado = new DADetalleTipoPago().InsertarDetalleTipoPago(Entidad);
                if (resultado > 0)
                {
                    //se evalua que falta pago y se redirecciona al mismo create para concretarlo
                    TempData["n"] = Entidad.IdComprobante;
                    return RedirectToAction("Create");
                }
                else
                {
                    return View(resultado);
                }
            }
            //pago de más recibe vuelto
            else
            {
                //se resta el pago para que sea exacto y dee 0
                Entidad.PagoDetallePago = Entidad.PagoDetallePago + Pagado;
                var resultado = new DADetalleTipoPago().InsertarDetalleTipoPago(Entidad);
                
                if (resultado > 0)
                {
                    return RedirectToAction("Index", "Comprobante");
                }
                else
                {
                    return View(resultado);
                }
            }
           
            //var model = new DADetalleComprobante();
           
        }

    }
}

WebAppVentaDSI/Views/DetalleComprobante/Create.cshtml
@model WebAppVentaDSI.Models.DetalleComprobante

@*@{
    ViewData["Title"] = "Ingreso";
}*@

<h1>Añadir Nuevo</h1>

<h3>Producto</h3>
<h4>@ViewBag.InfoTotal</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label>Cantidad</label>
                <input asp-for="CantidadDetalleComprobante" class="form-control" />
                <span asp-validation-for="CantidadDetalleComprobante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Producto</label>
                @*<input asp-for="IdProducto" class="form-control" />
                <span asp-validation-for="IdProducto" class="text-danger"></span>*@
                <select asp-for="IdProducto" class="form-control" asp-items="@(new SelectList(ViewBag.InfoProducto,"IdProducto","NombrePrecio"))"></select>
            </div>
            <div class="form-group">
                <label>Comprobante</label>
                @*<input asp-for="IdComprobante" class="form-control" />
                <span asp-validation-for="IdComprobante" class="text-danger"></span>*@
                
                <input asp-for="IdComprobante" class="form-control" value="@ViewBag.InfoComprobante" placeholder="@ViewBag.InfoComprobante" readonly />
                <span asp-validation-for="IdComprobante" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Agregar Producto" class="btn btn-primary btn-sm" />
                <a asp-action="Create" asp-controller="DetalleTipoPago"  role="button" class="btn btn-warning btn-sm">Pagar</a>
                <a asp-action="Index" asp-controller="Comprobante" role="button" class="btn btn-success btn-sm">Cancelar</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WebAppVentaDSI/Views/DetalleComprobante/Details.cshtml
@model WebAppVentaDSI.Models.DetalleComprobante


<h1>Detalle Producto</h1>

<div>
    <h4>DetalleComprobante</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdDetalleComprobante)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdDetalleComprobante)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CantidadDetalleComprobante)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CantidadDetalleComprobante)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Producto.NombreProducto)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Producto.NombreProducto)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdComprobante)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdComprobante)
        </dd>
    </dl>
</div>
<br />

<div>
    <a class="btn btn-primary btn-sm" role="button"asp-route-id="@Model.IdProducto" asp-action="Edit">Editar</a>
    <a class="btn btn-warning btn-sm" role="button" asp-action="Index">Atras</a>
@*    @Html.ActionLink("Editar", "Edit", new {  id = Model.IdDetalleComprobante  }) |
    @Html.ActionLink("Atras", "Index", new {  /*id = Model.IdDetalleComprobante*/  })*@
    @*<a asp-action="Index" class="btn btn-success btn-sm" role="button">Atras</a>*@
</div>

WebAppVentaDSI/Views/DetalleComprobante/Edit.cshtml
@model WebAppVentaDSI.Models.DetalleComprobante

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar - Datos</h1>

<h4>Producto del Comprobante</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <input type="hidden" asp-for="IdDetalleComprobante" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label>Comprobante</label>
                <input asp-for="IdDetalleComprobante" class="form-control" readonly />
                <span asp-validation-for="IdDetalleComprobante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Producto</label>
                @*<input asp-for="IdProducto" class="form-control" />
                <span asp-validation-for="IdProducto" class="text-danger"></span>*@
                <select class="form-control" asp-for="IdProducto" asp-items="@(new SelectList(ViewBag.ProductoEdit,"IdProducto","NombreProducto"))"></select>
            </div>
            <div class="form-group">
                <label>Cantidad</label>
                <input asp-for="CantidadDetalleComprobante" class="form-control" />
                <span asp-validation-for="CantidadDetalleComprobante" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Actualizar" class="btn btn-primary btn-sm" />
                <a asp-action="Index" role="button" class="btn btn-success btn-sm">Cancelar</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WebAppVentaDSI/Views/DetalleComprobante/Index.cshtml
@model IEnumerable<WebAppVentaDSI.Models.DetalleComprobante> 
<!--Para la paginacion-->
@using X.PagedList.Mvc.Core;
@using X.PagedList;
@using X.PagedList.Web.Common;
<!--inject role-->
@inject IAuthorizationService AuthorizationService

<br />
<h2 class="text-info">Detalle Productos</h2>
<br />
@*<form class="row"> 
    <div class="col-3">
        <input name="filterByName" class="form-control" placeholder="Ingrese Nombre"/>
    </div>
    <div class="col-4">
        <button class="btn btn-primary">Buscar</button>
    </div>
    <div div="col-3">
    </div>
    <!--para registrar-->
    <br />
</form>*@

<div class="col-3">
    @if ((await AuthorizationService.AuthorizeAsync(User, "AllowLayoutGerenteSupervisor")).Succeeded)
    {
        <a class="btn btn-primary btn-sm" role="button" asp-route-id="@TempData["IdComp"]" asp-action="Create" >Añadir Nuevo Producto</a>
      
    }
    @if ((await AuthorizationService.AuthorizeAsync(User, "AllowLayoutGerenteSupervisorVendedor")).Succeeded)
    {
        <a class="btn btn-success btn-sm" asp-action="Index" asp-controller="Comprobante">Atras</a> 
        @if ((ViewBag.DetPag) == "Cancelado")
        {
        }
        else
        {
            <a asp-action="Create" asp-controller="DetalleTipoPago" asp-route-id="@TempData["IdComp"]" role="button" class="btn btn-warning btn-sm">Pagar</a>

        }
    }
    
</div>
<br>


<table class="table table-hover table-bordered table-sm">
    <thead>
        <tr class="table-info">
            <th><center><strong>Cliente</strong></center></th>
            <th><center><strong>DNI</strong></center></th>
            <th><center><strong>Fecha Compra</strong></center></th>
            <th><center><strong>Comprobante</strong></center></th>
            <th><center><strong>Vendedor</strong></center></th>
            <th><center><strong>Producto</strong></center></th>
            <th><center><strong>Marca</strong></center></th>
            <th><center><strong>Precio</strong></center></th>
            <th><center><strong>Cantidad</strong></center></th>
            <th><center><strong>Total</strong></center></th>
            @if ((ViewBag.DetPag) == "Cancelado")
            {
            }else{
                @if ((await AuthorizationService.AuthorizeAsync(User, "AllowLayoutGerenteSupervisor")).Succeeded)
                {
                    <th><center><strong>Opciones</strong></center></th>
                }
            }
            
            @*<th>@TempData["IdComp"]</th>*@
        </tr>
    </thead>
    <tbody>
        @*@foreach (var item in Model)*@
        @for (int i = 0; i < (TempData["info"] as IEnumerable<WebAppVentaDSI.Models.DetalleComprobante>).Count(); i++)
        @*@for (int i = 0; i < Model.Count(); i++)*@
        {
            var item = (TempData["info"] as IEnumerable<WebAppVentaDSI.Models.DetalleComprobante>).ElementAt(i);
            var modelo = (ViewBag.Total as IList<double>).ElementAt(i);
            
            //int id = (ViewData["IdComp"] as IEnumerable<Comprobante>).ElementAt(0).IdComprobante;
            @*@if ( ViewData["IdComp"].ToString().Equals(item.IdComprobante.ToString()))
                    {
*@

                        <tr>
                        <td><center>@item.Comprobante.Cliente.NombresCompletos</center></td>
                        <td><center>@item.Comprobante.Cliente.DNICliente</center></td>
                        <td><center>@item.Comprobante.FechaEmisionComprobante.ToShortDateString()</center></td>
                        <td><center>@item.Comprobante.CodigoComprobante</center></td>
                        <td><center>@item.Comprobante.Empleado.NombresCompletos</center></td>
                        <td><center>@item.Producto.NombreProducto</center></td>
                        <td><center>@item.Producto.MarcaProducto.NombreMarcaProducto</center></td>
                        <td><center>@item.Producto.PrecioVentaProducto</center></td>
                        <td><center>@item.CantidadDetalleComprobante</center></td>
                        <td><center>@modelo</center></td>
                        @if((ViewBag.DetPag)=="Cancelado"){

                        }else{
                        @if ((await AuthorizationService.AuthorizeAsync(User, "AllowLayoutGerenteSupervisor")).Succeeded)
                        {
                        <td align="center">
                            <a class="btn btn-primary btn-sm" role="button" asp-route-id="@item.IdDetalleComprobante" asp-action="Edit">
                                <i class="fa fa-edit text-white" aria-hidden="true"></i>
                            </a>
                            <a class="btn btn-warning btn-sm text-white" role="button" asp-route-id="@item.IdDetalleComprobante" asp-action="Details">
                                <i class="fa fa-eye text-white" aria-hidden="true"></i>
                            </a>
                            <a class="btn btn-danger btn-sm" role="button" asp-route-id="@item.IdDetalleComprobante" asp-action="Delete">
                                <i class="fa fa-trash text-white" aria-hidden="true"></i>
                            </a>
                        </td>
                        }
                        }
                        
                    </tr>
                  @* }*@
        }
    </tbody>
</table>
<!--Paginacion-->
<div style ="display: flex; justify-content: center; align-items: center;">
    @Html.PagedListPager((IPagedList)TempData["info"],page=>Url.Action("Index","DetalleComprobante",new{page=page, id=TempData["IdComp"]}),PagedListRenderOptions.MinimalWithItemCountText)
</div>