WebAppVentaDSI/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebAppVentaDSI.Data.DataAcces;
using WebAppVentaDSI.Data.Interface;
using WebAppVentaDSI.Models;
using X.PagedList;

namespace WebAppVentaDSI.Controllers
{
    [Authorize]
    public class ClienteController : Controller
    {
        private readonly IDACliente DACliente;

        public ClienteController(IDACliente DACliente)
        {
            this.DACliente = DACliente;
        }

        public IActionResult Index(string filterByName, int page=1)
        {
            //pageNumnber:
            var pagenumber = page;

            //var model = new DACliente();
            var CL = DACliente.GetCliente();
            TempData["ID"] = "ID";
            TempData["NOM"] = "Nombre";
            TempData["APE"] = "Apellidos";
            TempData["DNI"] = "DNI";
            TempData["FECH"] = "Fecha de Nacimeinto";
            TempData["SEX"] = "Sexo";
            TempData["CEL"] = "Celular";
            TempData["DIRE"] = "Direccion";
            TempData["OPC"] = "Opciones";
            if (filterByName != null)
            {
                var filtro = (from tbl in CL
                              where tbl.NombreCliente.ToLower().Contains(filterByName.ToLower())
                              select tbl).ToList();
                var model = filtro.ToPagedList(pagenumber, 16);
                //TempData["CLIENTE"] = model;
                return View(model);
            }
            else
            {
                var model = CL.ToPagedList(pagenumber, 8);
                //TempData["CLIENTE"] = model;
                return View(model);
            }
        }

        public IActionResult Create()
        {

            //listar cliente
            //var infoCliente = new DACliente();
            ViewBag.InfoCliente = DACliente.GetCliente();


            return View();
        }

        [HttpPost]
        public IActionResult Create(Cliente Entidad)
        {
            Entidad.IdCliente = 0;
            //var model = new DACliente();
            var resultado = DACliente.InsertCliente(Entidad);
            if (resultado > 0)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(resultado);
            }
        }
        public IActionResult Edit(int id)
        {

            //var ClienteEdit = new DACliente();
            var resultado = DACliente.GetIdCliente(id);

            return View(resultado);
        }

        [HttpPost]
        public IActionResult Edit(Cliente cliente)
        {

            //var model = new DACliente();
            var resultao = DACliente.UpdatCliente(cliente);
            if (resultao)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(cliente);
            }
        }

        public IActionResult Details(int id)
        {
           // var datos = new DACliente();
            var model = DACliente.GetIdCliente(id);
            return View(model);
        }

        public IActionResult Delete(int id)
        {
            //var modelodelete = new DACliente();
            var resultado = DACliente.DeleteCliente(id);
            return RedirectToAction("Index");
        }
    }
}

WebAppVentaDSI/Controllers/EmpleadoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebAppVentaDSI.Data.DataAcces;
using WebAppVentaDSI.Data.Interface;
using WebAppVentaDSI.Models;
using X.PagedList;

namespace WebAppVentaDSI.Controllers
{
    [Authorize]
    public class EmpleadoController : Controller
    {
        private readonly IDAEmpleado DAEmpleado;
        private readonly IDACargoEmpleado DACargoEmpleado;
        private readonly IDADetalleEmpleado DADetalleEmpleado;

        public EmpleadoController(IDAEmpleado DAEmpleado, IDACargoEmpleado DACargoEmpleado, IDADetalleEmpleado DADetalleEmpleado)
        {
            this.DAEmpleado = DAEmpleado;
            this.DACargoEmpleado = DACargoEmpleado;
            this.DADetalleEmpleado = DADetalleEmpleado;
        }
        public List<string> GetEstado(IEnumerable<Empleado> empleado)
        {
            var estado = new List<string>();
            var detalle = DADetalleEmpleado.GetDetalleEmpleado();
           // var empleado = DAEmpleado.GetEmpleado();
            for (int i = 0; i<empleado.Count();i++)
            {

                var sql = (from tbl in detalle
                           where tbl.Empleado.IdEmpleado == empleado.ElementAt(i).IdEmpleado
                           orderby tbl.IdDetalleEmpleado descending
                           select tbl.Estado.NombreEstado).ToList();
                estado.Add(sql.ElementAt(0));
            }
            
            return estado;
        }
        public IActionResult Index(string filterByName, int page=1)
        {
            var pagenumber = page;
            //var model = new DAEmpleado();
            var EM = DAEmpleado.GetEmpleado();
            if (filterByName != null)
            {
                var filtro = (from tbl in EM
                              where tbl.NombreEmpleado.ToLower().Contains(filterByName.ToLower())
                              select tbl).ToList();
                var model = filtro.ToPagedList(pagenumber, 16);
                ViewData["ESTADO"] = GetEstado(filtro);
                ViewData["EM"] = model;
            }
            else
            {
                var model = EM.ToPagedList(pagenumber, 8);
                ViewData["ESTADO"]=GetEstado(model);
                ViewData["EM"] = model;
            }

            return View();
        }
        public IActionResult Create()
        {
            //Listar categoria
            //var infoCargo = new DACargoEmpleado();
            ViewBag.InfoCargo = DACargoEmpleado.GetCargoEmpleado();

            return View();
        }

        [HttpPost]
        public IActionResult Create(Empleado Entidad)
        {
            Entidad.IdEmpleado = 0;
           // var model = new DAEmpleado();
            var resultado = DAEmpleado.InsertEmpleado(Entidad);
            if (resultado > 0)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(resultado);
            }
        }
        public IActionResult Edit(int id)
        {
           // var CargoEdit = new DACargoEmpleado();
            ViewBag.CargoEdit = DACargoEmpleado.GetCargoEmpleado();

            //var model = new DAEmpleado();
            var resultado = DAEmpleado.GetIdEmpleado(id);
            return View(resultado);
        }

        [HttpPost]
        public IActionResult Edit(Empleado empleado)
        {

           // var model = new DAEmpleado();
            var resultao = DAEmpleado.UpdateEmpleado(empleado);
            if (resultao)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(empleado);
            }
        }

        public IActionResult Details(int id)
        {
            //var datos = new DAEmpleado();
            var model = DAEmpleado.GetIdEmpleado(id);
            return View(model);
        }

        public IActionResult Delete(int id)
        {
           // var modelodelete = new DAEmpleado();
            //var resultado = DAEmpleado.DeleteEmpleado(id);
            var tabladet = DADetalleEmpleado.GetDetalleEmpleado();

            var estado = (from tbl in tabladet where tbl.IdEmpleado==id orderby tbl.IdDetalleEmpleado descending select tbl.IdEstado).ToList();
            var estadoEmp = estado.ElementAt(0);
            if (estadoEmp == 1)
            {
                var detalle = new DetalleEmpleado();
                detalle.FechaDetalleEmpleado = DateTime.Now;
                detalle.IdEstado = 2;
                detalle.IdEmpleado = id;

                var resultado = DADetalleEmpleado.InsertDetalleEmpleado(detalle);
                if (resultado > 0)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(resultado);
                }

            }
            else if (estadoEmp == 2)
            {
                var detalle = new DetalleEmpleado();
                detalle.FechaDetalleEmpleado = DateTime.Now;
                detalle.IdEstado = 1;
                detalle.IdEmpleado = id;

                var resultado = DADetalleEmpleado.InsertDetalleEmpleado(detalle);
                if (resultado > 0)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(resultado);
                }
            }

            return RedirectToAction("Index");
        }
    }
}

WebAppVentaDSI/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebAppVentaDSI.Data.DataAcces;
using WebAppVentaDSI.Data.Interface;
using WebAppVentaDSI.Models;
using X.PagedList;

namespace WebAppVentaDSI.Controllers
{
    [Authorize]
    public class ProductoController : Controller
    {
        private readonly IDAProducto DAProducto;
        private readonly IDAMarcaProducto DAMarcaProducto;
        private readonly IDAFamiliaProducto DAFamiliaProducto;

        public ProductoController(IDAProducto DAProducto, IDAMarcaProducto DAMarcaProducto, IDAFamiliaProducto DAFamiliaProducto)
        {
            this.DAProducto = DAProducto;
            this.DAMarcaProducto = DAMarcaProducto;
            this.DAFamiliaProducto = DAFamiliaProducto;
        }

        public IActionResult Index(string filterByName, int page = 1)
        {
            var Producto = DAProducto.GetProducto();
            var pagenumber = page;
            if (filterByName != null)
            {
                var filtro = (from tbl in Producto
                              where tbl.NombreProducto.ToLower().Contains(filterByName.ToLower())
                              select tbl).ToList();
                var model = filtro.ToPagedList(pagenumber, 16);
                return View(model);
            }
            else
            {
                var model = Producto.ToPagedList(pagenumber, 8);
                return View(model);
            }
        }
        public IActionResult Create()
        {
            ViewBag.infoMarca = DAMarcaProducto.GetMarcaProducto();
            ViewBag.infofamilia = DAFamiliaProducto.GetFamiliaProducto();

            return View();
        }
        [HttpPost]
        public IActionResult Create(Producto Entidad)
        {
            //Entidad.FechaEmisionComprobante = DateTime.Now;
            Entidad.IdProducto = 0;
            //var model = new DAComprobante();
            var resultado = DAProducto.InsertarProducto(Entidad);
            if (resultado > 0)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(resultado);
            }
        }

        public IActionResult Edit(int id)
        {

            var resultado = DAProducto.GetIdProducto(id);
            ViewBag.infoMarca = DAMarcaProducto.GetMarcaProducto();
            ViewBag.infofamilia = DAFamiliaProducto.GetFamiliaProducto();

            return View(resultado);
        }

        [HttpPost]
        public IActionResult Edit(Producto producto)
        {

            var resultao = DAProducto.UpdateProducto(producto);
            if (resultao)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(producto);
            }
        }

        public IActionResult Details(int id)
        {
            // var datos = new DACliente();
            var model = DAProducto.GetIdProducto(id);
            return View(model);
        }

        public IActionResult Delete(int id)
        {
            //var modelodelete = new DACliente();
            var resultado = DAProducto.DeleteProducto(id);
            return RedirectToAction("Index");
        }
    }
}

WebAppVentaDSI/Views/Shared/_Layout.cshtml
<!--inject role-->
@inject IAuthorizationService AuthorizationService
<!--USUARIO TODO-->
@using Microsoft.AspNetCore.Identity
@using static WebAppVentaDSI.Data.ApplicationDbContext;
@inject SignInManager<Usuario> SignInManager
@inject UserManager<Usuario> UserManager
<!--END-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAppVentaDSI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebAppVentaDSI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAppVentaDSI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        @if ((await AuthorizationService.AuthorizeAsync(User, "AllowLayoutGerenteSupervisor")).Succeeded)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Empleado" asp-action="Index">Empleado</a>
                            </li> 
                        }
                        @if((await AuthorizationService.AuthorizeAsync(User, "AllowLayoutGerenteSupervisorVendedor")).Succeeded)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Index">Cliente</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Producto" asp-action="Index">Producto</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Comprobante" asp-action="Index">Vender</a>
                            </li>
                              
                        }
                                      
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebAppVentaDSI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>